### ISSUE TITLE
Queries returning null

### ISSUE THREAD

**Issue by AugustoCalaca** [entria/entria-fullstack#102]
The queries `node` and `user` are returning `null` through queries that are apparently correct:
```
query Q($id: ID!) {
  node(id: $id) {
    id
    ... on User {
      name
    }
  }
}

query Q($id: ID!) {
  user(id: $id) {
    id
    name
    email
    active
  }
}
```

The queries `me`, `users` and all mutations work normally and return the expected results, but `node` and `user` don't.

What is the reason for this result?

**Comment by sibelius** [comment]
viewer can see

**Comment by AugustoCalaca** [comment]
`const viewerCanSee = () => true;`

the problem was on the line below
https://github.com/entria/entria-fullstack/blob/d039809e5c5d87accd83819259a6256501bf8f31/packages/server/src/modules/user/UserType.ts#L12

I changed to `id: globalIdField('User, user => user._id')` and it worked.

**Comment by sibelius** [comment]
It is missing the map on user loader

this.id = data._id

**Comment by AugustoCalaca** [comment]
Is this not correct?

https://github.com/entria/entria-fullstack/blob/d039809e5c5d87accd83819259a6256501bf8f31/packages/server/src/modules/user/UserLoader.ts#L23-L25

**Comment by sibelius** [comment]
Maybe this is the bug

**Comment by AugustoCalaca** [comment]
any tips or ideas to solve this?

**Comment by sibelius** [comment]
Change the line and add a test
