### ISSUE TITLE
Error running relay web

### ISSUE THREAD

**Issue by itelo** [entria/entria-fullstack#120]
Hello everyone, when I run `yarn relay: web` i got the exit code 100, so I tried to run the command inside the web package, but now I'm getting:

![image](https://user-images.githubusercontent.com/11433064/69914801-2ed1c180-1427-11ea-9bef-8f1a5cf3722b.png)

**Comment by sibelius** [comment]
You need to upgrade graphql version, and also make sure all relay versions matches

**Comment by sibelius** [comment]
`yarn workspace @entria/web relay` is working well for me

can you try to `yarn`?

**Comment by sibelius** [comment]
check this https://github.com/entria/entria-fullstack/pull/125

web is fixed
