### ISSUE TITLE
Update Web dependencies

### ISSUE THREAD

**Issue by lucas-mdiniz** [entria/entria-fullstack#138]
- [ ] The version of `react-relay` (^0.0.0-experimental-a1a40b68) is deprecated and causing errors to run the Web package.

- [ ] There are 2 versions of `relay-runtime` installed, one as dev dependecy at `5.0.0 `an one as a normal dependency at `7.1.0`

To successfully run the package I had to remove `relay-runtime` from the dev dependencies and update:

- relay-runtime

- relay compiler

- babel-plugin-relay

- graphql

- relay-compiler-language-typescript

- react

- react-dom

- react-relay

After all the updates I had to use `unstable_createRoot` at `ReactDOM.createRoot(root).render(<App />);`

Another problem that I faced is that after all the updates there were 2 versions of `React` being used on the package, one from the App and one from the Web. To solve that I add a alias to `react` in `webpack.config.js`:

`resolve: {
    alias: {
      react: resolve('./node_modules/react')
    }
  },`

I'll be happy to make a PR on this issue, let me know if there are a better solution for some of my approaches or if I should proceed with the PR.

**Comment by sibelius** [comment]
I'm up to simplify this a bit

Let's update based on https://github.com/sibelius/relay-workshop

You can update all dependencies

let's remove `app` and `app-expo`, let's focus on `web` it is simpler

we can also remove `restria`, no need for REST right now

**Comment by lucas-mdiniz** [comment]
I've deleted `app`, `app-expo` and `restria`, and updated all dependencies. 

If anyone ever needs it, the repo is here [entria-web](https://github.com/lucas-mdiniz/entria-web). 

Don't know if this should be a PR, and if yes how it would be merged (as I deleted some packages). 

Anyway, the web and the server are working now, thanks for your help and for the Playground.

**Comment by sibelius** [comment]
You can send a Pr and we can review and merge it

**Comment by dantxal** [comment]
The focus on web is valid for anyone doing the challenge?

**Comment by sibelius** [comment]
We can also update the challenge to focus on web

Web or react native won't change

The more important parts are the concepts
