### ISSUE TITLE
Error running start:server

### ISSUE THREAD

**Issue by vmamore** [entria/entria-fullstack#139]
Hello guys, i'm trying to run the project but when I run 'yarn start:server' I'm getting this error message:
![image](https://user-images.githubusercontent.com/26505439/96619796-96f5f400-12d4-11eb-8b9a-48a1e1eb04cb.png)

I saw that was a problem trying to connect to Mongo so I decided to run the docker compose but I'm receiving this message:
![image](https://user-images.githubusercontent.com/26505439/96619921-b9880d00-12d4-11eb-9fa6-063e029164a5.png)

Can you guys help me identify what I'm doing wrong?

Thanks!

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/96622226-0d4c2380-12e0-11eb-9b33-f9aebc528f5a.png)

make sure mongo is running in your machine, or use a  different .env from mongo atlas

**Comment by vmamore** [comment]
Worked!

Thanks
