### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by thiagoleitedev** [entria/entria-fullstack#42]
![image](https://user-images.githubusercontent.com/6524612/50541242-1e162d00-0b80-11e9-829b-121534a9fc32.png)

**Comment by sibelius** [comment]
have you tried to use latest version of graphql-mongoose-loader?

**Comment by sibelius** [comment]
this is a problem with `jsnext:main` field of graphql-mongoose-loader

**Comment by sibelius** [comment]
http://2ality.com/2017/06/pkg-esnext.html

**Comment by jaburcodes** [comment]
still facing

**Comment by sibelius** [comment]
follow the command above

**Comment by thiagoleitedev** [comment]
I tried today the new version of graphql-mongoose-loader, which came out today and worked perfectly! I'm going to make a PR for version update
