### ISSUE TITLE
remote cache react native

### ISSUE THREAD

**Issue by sibelius** [entria/entria-fullstack#52]
check cache store format here https://github.com/facebook/metro/blob/master/packages/metro-cache/src/stores/HttpStore.js

- [ ] implement server routes GET/PUT to get cached data

check docs here https://facebook.github.io/metro/docs/en/caching#cache-fetching-saving

**Comment by jgcmarins** [comment]
maybe this: https://github.com/mrtnzlml/quick-payments/issues/24
