### ISSUE TITLE
webpack package

### ISSUE THREAD

**Issue by sibelius** [entria/entria-fullstack#55]

**Comment by PlayMa256** [comment]
The ideia of it would be just to centralize configurations for projects and keep dependencies specifically there, or to actually abstract the configurations to be used in most packages?

**Comment by sibelius** [comment]
it could be similar to babel package https://github.com/entria/entria-fullstack/blob/master/packages/web/babel.config.js#L1

we could have most common configs, and use webpack merge or something to override some of them

**Comment by PlayMa256** [comment]
Let's do this after we have #46 merged, it has few improvements and changes we can use and abstract to another package as well, otherwise duplicated work is going to be done.
