### ISSUE TITLE
add web package

### ISSUE THREAD

**Issue by sibelius** [entria/entria-fullstack#6]

**Comment by jgcmarins** [comment]
- [ ] it should focus on mobile first
- [ ] it should have a sw
- [ ] it should work with ts

**Comment by sibelius** [comment]
related to https://github.com/entria/entria-fullstack/pull/7

**Comment by sibelius** [comment]
check this as well

https://github.com/sibelius/webpack-debug

**Comment by sibelius** [comment]
done
