### ISSUE TITLE
add metro.config.js to work well on workspaces

### ISSUE THREAD

**Issue by sibelius** [entria/entria-fullstack#67]
https://gist.github.com/sibelius/14d0ecdbd917959c0f7b6f1c4f81f850

**Comment by sibelius** [comment]
more sutff here https://gist.github.com/sibelius/53b3ea832d9b0d46b7b3903c6d842b85

**Comment by Braden1996** [comment]
> more sutff here https://gist.github.com/sibelius/53b3ea832d9b0d46b7b3903c6d842b85
Thanks - that is super helpful!

Although, I kept getting the error: https://reactjs.org/warnings/invalid-hook-call-warning.html

**Comment by sibelius** [comment]
try this `nohoist`
```jsx
"nohoist": [
      "**/react-native",
      "**/react-native-*",
]
```

**Comment by Braden1996** [comment]
> try this `nohoist` on root package.json
> 
> ```js-jsx
> "workspaces": {
>     "packages": [
>       "packages/*"
>     ], 
>     "nohoist": [
>       "**/react-native",
>       "**/react-native-*",
>     ]
> }
> ```

After some digging, it seemed that I had two physical versions of React on-disk. My application was using both of them, which broke hooks. I fixed this by adding the following to my root:
```
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/react",
      "**/react/**"
    ]
  }
```
