### ISSUE TITLE
Errror with styled-components

### ISSUE THREAD

**Issue by thiagoleitedev** [entria/entria-fullstack#72]
I have cloned the repository> yarn install> yarn start
and.. =(

![image](https://user-images.githubusercontent.com/6524612/56526013-24128e00-6522-11e9-9315-802a1c025aef.png)

**Comment by PlayMa256** [comment]
Some still seeing this issue.

**Comment by kuttim** [comment]
Seeing 
![image](https://user-images.githubusercontent.com/41844956/57859482-b6ddda00-77fb-11e9-86db-8cc880671e8c.png) @PlayMa256

**Comment by PlayMa256** [comment]
Are you able to see exactly where it is coming from? (line 794 on bundle.js)

**Comment by kuttim** [comment]
Yep, here how it looks.
![image](https://user-images.githubusercontent.com/41844956/57860214-243e3a80-77fd-11e9-85f7-1054210b0d84.png)

**Comment by PlayMa256** [comment]
@kuttim pr opened, #81 to fix this.

**Comment by PlayMa256** [comment]
@kuttim merged.

**Comment by kuttim** [comment]
@PlayMa256 Works, going to open another issue regarding start up scripts.
