### ISSUE TITLE
Not able to start everything (server, app, web)

### ISSUE THREAD

**Issue by kuttim** [entria/entria-fullstack#83]
Was looking around the issues and couldn't see anything related to this, how ever if there is already something like this stated, sorry.
I'm not able to run everything with one command (`yarn start`)

Node version: v10.15.3
Npm version: v6.4.1
Yarn version: 1.15.2

Context: When I run yarn start, which should start all services (web, server, mobile) it only starts on the server part, I assume it somehow hangs on that because it never proceeds to web or mobile package, here's a screenshot of how it looks after 10 minutes using `yarn start`  command.
![image](https://user-images.githubusercontent.com/41844956/57872828-43e15d00-7815-11e9-9d6b-2098e0dbceb7.png)

**Comment by sibelius** [comment]
Can you run each one of the start commands separately?

**Comment by kuttim** [comment]
@sibelius `yarn start:web` works perfectly.
![image](https://user-images.githubusercontent.com/41844956/57872956-a20e4000-7815-11e9-9d5e-59ad068d37f8.png)
`yarn start:app` also works 
![image](https://user-images.githubusercontent.com/41844956/57873032-d97cec80-7815-11e9-842a-0966bb06b4aa.png)
and `yarn start:server` works standalone as well.

**Comment by sibelius** [comment]
I think we can deprecate `yarn start`, does not make sense to run all commands at once

maybe server and app
or server and web

**Comment by kuttim** [comment]
However I tried to add custom command called start:ui for example
`"start:ui": "yarn start:web && yarn start:server"` and it seems to be hanging on the first task as well.

**Comment by robertoachar** [comment]
> and it seems to be hanging on the first task as well.

In bash `&&` means `AND`. If the first command completes successfully then run the next one.

In bash `&` means that the preceding command should run in the background.

So...:wink:

```json
"start:ui": "yarn start:web & yarn start:server"
```

**Comment by kuttim** [comment]
Aha!
