### ISSUE TITLE
Tests failing when running tests

### ISSUE THREAD

**Issue by matheus1lva** [entria/entria-fullstack#84]
`Invariant Violation: graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `graphql`.

That happens, although a custom transformer had already being added on #82, but had no success.
If you have any ideas, you can push commits or comment on that PR

**Comment by kuttim** [comment]
@PlayMa256 How does your dev setup look like? I'm getting completely different error when I use master branch which makes it hard to reproduce in that case.
