### ISSUE TITLE
use bcryptjs instead of bcrypt

### ISSUE THREAD

**Issue by sibelius** [entria/entria-fullstack#87]
bcrypt causes a lot of pain to install in some machines

**Comment by mauriciord** [comment]
Which package do you want to use it? Because i found bcryptjs on types in server package

**Comment by sibelius** [comment]
just remove all usages of  `bcrypt`

**Comment by mauriciord** [comment]
I'm closing this issue because I didn't find `bcrypt` usage anymore.

**Comment by julioxavierr** [comment]
This dependency doesn't seem to be used either @mauriciord 

https://github.com/entria/entria-fullstack/blob/e931029acd75d363bfba35c4105dbf34d4c927c4/packages/restria/package.json#L8

**Comment by rafaelangical** [comment]
I'am receiving errors relationed to bcrypt while try install dependencies.

**Comment by rafaelangical** [comment]
`make: *** [bcrypt_lib.target.mk:103: Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rafael/.config/yarn/global/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.0.0-21-generic
gyp ERR! command "/home/rafael/.nvm/versions/node/v10.15.3/bin/node" "/home/rafael/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/rafael/fullstack-app/node_modules/bcrypt
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.3
`

**Comment by sibelius** [comment]
try to upgrade to latest version of bcrypt

**Comment by rafaelangical** [comment]
resolved PR #91

**Comment by sibelius** [comment]
fixed again here https://github.com/entria/entria-fullstack/pull/91
