### ISSUE TITLE
Docker-compose configuration failing

### ISSUE THREAD

**Issue by renanmav** [entria/entria-fullstack#93]
Okay, I'll list the issues:

1. Thinking on monorepo, in the root, I'd like to start the development server with docker-compose. I can't do it. 

2. Still in the root path, I'd like to build the server image with Docker and orchestrate the containers by myself. Tried with `docker build -f packages/server/Dockerfile .` and got this error:
```bash
Step 8/9 : RUN npm run build
 ---> Running in 002a83d6bd5c
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-06T19_31_07_179Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
```
The top-level `package.json` doesn't have the build script.

3. In `packages/server` we have a `docker-compose.yml`. Updating the entrypoint to `npm run start` (see #92 ), when we run it:
```bash
Step 8/9 : RUN npm run build
 ---> Running in 5536b3fd6b71

> @entria/server@0.0.1 build /app
> npm run clear && babel src --extensions ".es6,.js,.es,.jsx,.mjs,.ts" --ignore *.spec.js --out-dir dist --copy-files


> @entria/server@0.0.1 clear /app
> rimraf ./dist

sh: 1: rimraf: not found
```
Talking to @sibelius, we thought that Docker context is wrong and isn't recognizing the packages installed on `node_modules`.

**Comment by sibelius** [comment]
check this https://gist.github.com/sibelius/8ae1edd6603658da5f9e6dcf63465aa7
